### ISSUE TITLE
Rewrite rules flushed every page load

### ISSUE THREAD

**Issue by AaronDDM** [getherbert/framework#11]
Hi,

I just recently started using this framework, and it is looking promising.

I did however notice one thing and I am not sure if this is by deign: on every page load, the rewrite rules are being flushed. Technically, this is only really needed at plugin activation.

Is there a reason for this? (Router -> construct -> add_action('wp_loaded', [$this, 'flush']);)

**Comment by panvagenas** [comment]
Actually this is bad practice as stated in [WordPress Codex](https://codex.wordpress.org/Function_Reference/flush_rewrite_rules#Usage).

**Comment by jeremyzahner** [comment]
@jasonagnew Could you give us a statement on that matter?
