### ISSUE TITLE
Did this project die?

### ISSUE THREAD

**Issue by csrui** [getherbert/framework#16]
No updates on this guys?

**Comment by JacobDorman** [comment]
... also wondering

**Comment by PrafullaKumarSahu** [comment]
I am too curious about this as no response from the developer neither any  update on framework.

**Comment by jeremyzahner** [comment]
@csrui @JacobDorman @PrafullaKumarSahu Seems like there are discussions taking place right now on who will be maintaining this project further. I guess you will get your answer pretty soon. =) CC: @onnimonni

**Comment by PrafullaKumarSahu** [comment]
@jeremyzahner  This is too old my dear friend, my mistake, I could have replied, I have already created a plugin using this and @jasonagnew  helped me a lot on that . thanks to him :+1:  and about future, It is really good to know there will be updates :)
