### ISSUE TITLE
Fatal error: Declaration of Herbert\Framework\Application::make() must be compatible

### ISSUE THREAD

**Issue by Simpfc** [getherbert/framework#3]
Hi guys! Could you help me? When I try to activate plugin I get this error:

**Fatal error: Declaration of Herbert\Framework\Application::make() must be compatible with Illuminate\Contracts\Container\Container::make($abstract, array $parameters = Array) in /var/www/spinazdorov/htdocs/wp-content/plugins/Klinocs3/vendor/getherbert/framework/Herbert/Framework/Application.php on line 8**

http://joxi.ru/Y2L8gpEfO8z926
Unfortunatly, I don't understand how fix it. Tell me please, how could I fix it? 
May be I do something wrong ?
Thanks!

UPD: Sorry,I wanted to write here  https://github.com/getherbert/herbert/tree/rewrite

**Comment by ghost** [comment]
have a look here: https://github.com/getherbert/framework/issues/2

**Comment by jasonagnew** [comment]
Thanks, this is fixed now.
