### ISSUE TITLE
Application class not implementing Illuminate interface

### ISSUE THREAD

**Issue by yavormilchev** [getherbert/framework#47]
### File
https://github.com/getherbert/framework/blob/dev/Herbert/Framework/Application.php#L12

### Issue Description
1. I create a new project using the plugin skeleton at https://github.com/getherbert/herbert
2. Run `composer install`
3. Activate the plugin and see the following error:

```
Fatal error: Class Herbert\Framework\Application contains 3 abstract methods
and must therefore be declared abstract or implement the remaining methods
(Illuminate\Contracts\Foundation\Application::runningInConsole,
Illuminate\Contracts\Foundation\Application::runningUnitTests,
Illuminate\Contracts\Foundation\Application::getCachedPackagesPath) in
.../vendor/getherbert/framework/Herbert/Framework/Application.php on line 12
```

**Comment by mitchierichie** [comment]
@yavormilchev I just had this issue too, why is this closed? Did you find a workaround?
